### ISSUE TITLE
Example of 'applications' column in the credentials data

### ISSUE THREAD

**Issue by aephidayatuloh** [datastorm-open/shinymanager#33]
Hi,

I need to create different apps for different group of users based on their login information. I read on the `create_db`'s help page with applications column.

**applications (optional)** : the name of the applications to which the user is authorized, separated by a semicolon. The name of the application corresponds to the name of the directory, or can be declared using : options("shinymanager.application" = "my-app")

I added the `applications = c("app1", "app2")`  for credentials data.frame.
```
credentials <- data.frame(
  user = c("shiny", "shinymanager"),
  password = c("12345", "12345"),
  applications = c("app1", "app2"),
  stringsAsFactors = FALSE
)
```
I got an error when I login
![image](https://user-images.githubusercontent.com/11643631/81703195-72306180-9496-11ea-8f24-d50337641099.png)

I created `app1` and `app2` folders inside the working directory. The structure looks like this.

```
myapp
| - www
| - data
| - app1
| - app2
```

Could you give me example to use this feature? Thanks

**Comment by guivivi** [comment]
Dear shinymanager maintainers,

Many thanks for your outstanding package. I have a similar concern with the 'applications' column in the credentials data. I have tried several things but they are not working. 

What type of folders tree do we have to set so that your code works?

Diving into your code, I think a problem may come from the definition of the get_appname function:
get_appname <- function() {
  getOption("shinymanager.application", default = basename(getwd()))
}

To the best of my knowledge, this is only giving the parent directory, but in order to find the subapplications, we should use something like that:
get_appname <- function() {
  getOption("shinymanager.application", default = basename(list.dirs(getwd())))
}

This question is also related to the issue #31 one login page many apps. Would this 'applications' column allow us to login in different apps with the same password?

I would be very grateful if you could give us some insights about this.

Many thanks again.

Kind regards,

Guillermo

**Comment by StatisMike** [comment]
@aephidayatuloh I am currently creating an app tree similiar to yours. I'm using syntax similiar to yours and everything seems to be working fine. 

The problem seems to be that every app folder should be in the same directory, as per:

```
myapps
| - www
| - data
| - myapp
| - app1
| - app2
```

There should not be an app inside 'myapps' directory - it should only contain folders containing all shiny apps. 

Moreover, if you need some user to access many apps, you need to give its value in the form of:

`applications = "myapp;app1;app2" `

@guivivi: as the folder structure you can use the one given above. You can use the same password and username for multiple applications - even without specifying `applications` argument (thought every user can access every app then). You just need all to point `check_credentials` function of all apps within one folder to one database.

Though I would like to point it out that this feature isn't explained in detail in the documentation.

**Comment by guivivi** [comment]
Hello, many thanks for the response. I take note as a further expansion of my apps.
Many thanks also for the package.

**Comment by aephidayatuloh** [comment]
Thank for your response @StatisMike, 

If should be no "app.R" or "server.R" in myapps folder (as your directory structure), where the "main app" should be saved? Is it inside myapp folder? And where the sqlite database file should be?

How should I restructure my app? FYI, I'm saving the sqlite database file in data folder.

**Comment by StatisMike** [comment]
@aephidayatuloh I'm sorry I weren't clearer.

In the present version of `shinymanager` there is no "main app". All apps are fully equivalent, and the directory structure should be too. I will present the way I've coped with using one for management of accounts with that limitation.

To be clearer, the structure should look like:

```
- my apps
  - simple_app
    - app.R
  - complex_app
    - ui.R
    - server.R
    - global.R
  - management_app
    - app.R
    - data
      - data.sqlite
```

All apps are using the same `data.sqlite` database (calling to `../main_app/data/data.sqlite` for `simple_app` and `complex_app`). The management app is empty app containing only `secure_app` and `secure_ui` modules for account management.

You can inlude admin mode and admin accounts in `simple_app` and/or `complex_app`, but you need to specify the way that the admins of these can input `applications` value if you need to limit their possibilities. To do that, specify inputs_list in their `secure_app` functions as in example:

```
inputs_list = list(
    applications = list( fun = "selectInput", 
                                  args = list(choices = "simple_app") ) ) )
# that way admin of simple_app can only create users with authorization for simple_app, not complex_app
```

Of course that kind of implementation seems reduntant with only two functional apps (it is simpler to set `enable_admin = F` inside both apps, only keeping it in `management_app`, or not bother with the latter and just use two apps with admin mode enabled). It seems handy when you have more apps.

Though, it is important that if you want to make different levels of authorization (for one, two, and all apps) in the app that you don't intend its admin to have full control for giving access to all apps, you should implement `input_list` like that:

```
inputs_list = list(
    applications = list( fun = "selectInput", 
                                  args = list(choices = c("Only one app" = "simple_app",
                                                                      "Two apps" = "simple_app;complex_app" ) ) 
) ) )
```
This way the admin of this app can only give user access to `simple_app` or both `simple_app` and `complex_app`. There is no way for him to give access to `management_app`, as it is allowed only for highest level of authorization.

**Comment by aephidayatuloh** [comment]
Thanks @StatisMike, this way more clearer.

I tried to create a simple app for reproducible.

```
myapps  
| - app1      
|    - app.R   # the app is what I copied from shiny::runExample("01_hello")
| - app2      
|    - app.R   # I copied from shiny::runExample("11_timer")
| - management_app   
|    - app.R                    
|    - data
| - database.sqlite
```
The inside of app.R in management_app is like this:

```
library(shiny)
library(shinymanager)

ui <- fluidPage(
  tags$h2("My secure application")
)

ui <- secure_app(ui, enable_admin = TRUE)

server <- function(input, output, session){
  res_auth <- secure_server(
    check_credentials = "database.sqlite")
}

shinyApp(ui, server)

```
Where the credentials database I created using: 
```
credentials <- data.frame(
   user = c("shiny", "shinymanager"),
   password = c("12345", "12345"),
   applications = c("app2", "app1:app2"),
   stringsAsFactors = FALSE
)
 create_db(credentials, "database.sqlite")
```

When I run the app with `shiny::runApp()`, the app doesn't show up and error popped up (as expected because there is no apps in myapps folder).
```
shiny::runApp()
Error: App dir must contain either app.R or server.R.
Run `rlang::last_error()` to see where the error occurred.
``` 

Then I tried to run with `shiny::runApp('management_app')`
```
shiny::runApp(management_app)
# Listening on http://127.0.0.1:3991
```
The login page showed up 
![image](https://user-images.githubusercontent.com/11643631/123495670-dab4b080-d64e-11eb-9415-783dacb6878a.png)

But when I login using those account, the app disappear and error popped up.
```
Warning: Error in : 'db' must be a data.frame or a path to a SQLite database
  1: runApp
```

How can I fix this?
